/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/ai-projects': RouteRecordInfo<'/ai-projects', '/ai-projects', Record<never, never>, Record<never, never>>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/giving-talks': RouteRecordInfo<'/giving-talks', '/giving-talks', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/111': RouteRecordInfo<'/posts/111', '/posts/111', Record<never, never>, Record<never, never>>,
    '/posts/async-with-composition-api': RouteRecordInfo<'/posts/async-with-composition-api', '/posts/async-with-composition-api', Record<never, never>, Record<never, never>>,
    '/posts/batchInsert': RouteRecordInfo<'/posts/batchInsert', '/posts/batchInsert', Record<never, never>, Record<never, never>>,
    '/posts/batchInsert-boom': RouteRecordInfo<'/posts/batchInsert-boom', '/posts/batchInsert-boom', Record<never, never>, Record<never, never>>,
    '/posts/binfe-2020-zh': RouteRecordInfo<'/posts/binfe-2020-zh', '/posts/binfe-2020-zh', Record<never, never>, Record<never, never>>,
    '/posts/forgeted-keyword-transient': RouteRecordInfo<'/posts/forgeted-keyword-transient', '/posts/forgeted-keyword-transient', Record<never, never>, Record<never, never>>,
    '/posts/icons-in-pure-css': RouteRecordInfo<'/posts/icons-in-pure-css', '/posts/icons-in-pure-css', Record<never, never>, Record<never, never>>,
    '/posts/icons-in-pure-css-zh': RouteRecordInfo<'/posts/icons-in-pure-css-zh', '/posts/icons-in-pure-css-zh', Record<never, never>, Record<never, never>>,
    '/posts/introduction-to-vitest-vue-nation-2022': RouteRecordInfo<'/posts/introduction-to-vitest-vue-nation-2022', '/posts/introduction-to-vitest-vue-nation-2022', Record<never, never>, Record<never, never>>,
    '/posts/Is-the-HTML-in-vue-files-real-HTML': RouteRecordInfo<'/posts/Is-the-HTML-in-vue-files-real-HTML', '/posts/Is-the-HTML-in-vue-files-real-HTML', Record<never, never>, Record<never, never>>,
    '/posts/Jarvis': RouteRecordInfo<'/posts/Jarvis', '/posts/Jarvis', Record<never, never>, Record<never, never>>,
    '/posts/journey-with-icons': RouteRecordInfo<'/posts/journey-with-icons', '/posts/journey-with-icons', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-dx-2023': RouteRecordInfo<'/posts/nuxt-dx-2023', '/posts/nuxt-dx-2023', Record<never, never>, Record<never, never>>,
    '/posts/patterns-of-vueuse-vuefes-japan-2022': RouteRecordInfo<'/posts/patterns-of-vueuse-vuefes-japan-2022', '/posts/patterns-of-vueuse-vuefes-japan-2022', Record<never, never>, Record<never, never>>,
    '/posts/reason-for-QR-code-crash': RouteRecordInfo<'/posts/reason-for-QR-code-crash', '/posts/reason-for-QR-code-crash', Record<never, never>, Record<never, never>>,
    '/posts/reimagine-atomic-css': RouteRecordInfo<'/posts/reimagine-atomic-css', '/posts/reimagine-atomic-css', Record<never, never>, Record<never, never>>,
    '/posts/reimagine-atomic-css-zh': RouteRecordInfo<'/posts/reimagine-atomic-css-zh', '/posts/reimagine-atomic-css-zh', Record<never, never>, Record<never, never>>,
    '/posts/The-basic-concepts-of-framework-design': RouteRecordInfo<'/posts/The-basic-concepts-of-framework-design', '/posts/The-basic-concepts-of-framework-design', Record<never, never>, Record<never, never>>,
    '/posts/typed-provide-and-inject-in-vue': RouteRecordInfo<'/posts/typed-provide-and-inject-in-vue', '/posts/typed-provide-and-inject-in-vue', Record<never, never>, Record<never, never>>,
    '/posts/vue-beijing-2021': RouteRecordInfo<'/posts/vue-beijing-2021', '/posts/vue-beijing-2021', Record<never, never>, Record<never, never>>,
    '/posts/vueuse-best-practice-vueconf-china-2022': RouteRecordInfo<'/posts/vueuse-best-practice-vueconf-china-2022', '/posts/vueuse-best-practice-vueconf-china-2022', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors-list': RouteRecordInfo<'/sponsors-list', '/sponsors-list', Record<never, never>, Record<never, never>>,
    '/streams': RouteRecordInfo<'/streams', '/streams', Record<never, never>, Record<never, never>>,
    '/talks': RouteRecordInfo<'/talks', '/talks', Record<never, never>, Record<never, never>>,
  }
}
