/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/ai-projects': RouteRecordInfo<'/ai-projects', '/ai-projects', Record<never, never>, Record<never, never>>,
    '/algorithm/': RouteRecordInfo<'/algorithm/', '/algorithm', Record<never, never>, Record<never, never>>,
    '/algorithm/01-two-sum': RouteRecordInfo<'/algorithm/01-two-sum', '/algorithm/01-two-sum', Record<never, never>, Record<never, never>>,
    '/giving-talks': RouteRecordInfo<'/giving-talks', '/giving-talks', Record<never, never>, Record<never, never>>,
    '/link/': RouteRecordInfo<'/link/', '/link', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/111': RouteRecordInfo<'/posts/111', '/posts/111', Record<never, never>, Record<never, never>>,
    '/posts/batchInsert': RouteRecordInfo<'/posts/batchInsert', '/posts/batchInsert', Record<never, never>, Record<never, never>>,
    '/posts/batchInsert-boom': RouteRecordInfo<'/posts/batchInsert-boom', '/posts/batchInsert-boom', Record<never, never>, Record<never, never>>,
    '/posts/forgeted-keyword-transient': RouteRecordInfo<'/posts/forgeted-keyword-transient', '/posts/forgeted-keyword-transient', Record<never, never>, Record<never, never>>,
    '/posts/icons-in-pure-css': RouteRecordInfo<'/posts/icons-in-pure-css', '/posts/icons-in-pure-css', Record<never, never>, Record<never, never>>,
    '/posts/icons-in-pure-css-zh': RouteRecordInfo<'/posts/icons-in-pure-css-zh', '/posts/icons-in-pure-css-zh', Record<never, never>, Record<never, never>>,
    '/posts/Is-the-HTML-in-vue-files-real-HTML': RouteRecordInfo<'/posts/Is-the-HTML-in-vue-files-real-HTML', '/posts/Is-the-HTML-in-vue-files-real-HTML', Record<never, never>, Record<never, never>>,
    '/posts/Jarvis': RouteRecordInfo<'/posts/Jarvis', '/posts/Jarvis', Record<never, never>, Record<never, never>>,
    '/posts/journey-with-icons': RouteRecordInfo<'/posts/journey-with-icons', '/posts/journey-with-icons', Record<never, never>, Record<never, never>>,
    '/posts/reason-for-QR-code-crash': RouteRecordInfo<'/posts/reason-for-QR-code-crash', '/posts/reason-for-QR-code-crash', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
  }
}
