name: Sync to CNB

on:
  push:
    branches:
      - main    # You can specify which branches to trigger the action on
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Sync to CNB Repository
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/rookie-stack/liujiapeng.me.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.CNB_TOKEN }} \
            -e PLUGIN_BRANCH="main" \
            -e PLUGIN_GIT_USER="cnb" \
            -e PLUGIN_GIT_EMAIL="cnb@cnb.cool" \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
